apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-cicd
  labels:
    app: python-cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-cicd
  template:
    metadata:
      labels:
        app: python-cicd
    spec:
      containers:
      - name: python-cicd
        image: 713332525966.dkr.ecr.ap-south-1.amazonaws.com/python-cicd-demo:21-807fb2f
        ports:
        - containerPort: 8080
