apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-cicd
  labels:
    app: python-cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-cicd
  template:
    metadata:
      labels:
        app: python-cicd
    spec:
      nodeSelector:
        eksctl.io/nodegroup-name: ng-registry-ca
      imagePullSecrets:
      - name: nexus-regcred
      containers:
      - name: python-cicd
        image: registry.nexus.internal/python-cicd-demo:17-5b04bbf
        ports:
        - containerPort: 8080
